title: José Pedro Pinto
url: 'https://jpedropinto.com'

theme_skin: green
chrome_mobile_color: 42A8C0

# Tracker
analytics: G-HKDQ9XFZ5Q

# Sass/SCSS
sass:
  sass_dir: _sass

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: localhost
safe: true
